{
  pkgs-unst,
  quickshell,
  swww,
  zen-browser,
  user,
  ...
}:
{
  imports = [
    ./home.nix
    ./config.nix
    ./modules/dev.nix
    ./modules/file.nix
    ./modules/gaming.nix
    ./modules/shell.nix
    ./modules/theme.nix
    ./modules/video.nix
  ];

  home.packages = with pkgs-unst; [
    adwaita-icon-theme
    alsa-scarlett-gui
    android-tools
    btop
    digikam
    dunst
    file
    fragments
    helix
    hyprshot
    jmtpfs
    kitty
    lazygit
    nano
    miru
    nerd-fonts.symbols-only
    nix-output-monitor
    quickshell.packages.${user.system}.default
    p7zip-rar
    progress
    rofi-wayland
    swww.packages.${user.system}.swww
    teamspeak6-client
    thunderbird
    vesktop
    wev
    zen-browser.packages.${user.system}.default
    zed-editor
  ];
}
