{
  pkgs,
  swww,
  zen-browser,
  user,
  ...
}:
{
  imports = [
    ./home.nix
    ./config.nix
    ./modules/dev.nix
    ./modules/file.nix
    ./modules/gaming.nix
    ./modules/shell.nix
    ./modules/theme.nix
    ./modules/video.nix
  ];

  home.packages = with pkgs; [
    adwaita-icon-theme
    ags
    alsa-scarlett-gui
    android-tools
    btop
    dunst
    file
    fragments
    helix
    hyprshot
    kitty
    nano
    nerd-fonts.symbols-only
    p7zip-rar
    rofi-wayland
    swww.packages.${user.system}.swww
    vesktop
    wev
    zen-browser.packages.${user.system}.default
    zed-editor
  ];
}
