################
### MONITORS ###
################
monitor=HDMI-A-1,3840x2160@120,0x0,1
monitor=DP-2,1920x1080@120,-1080x100,1,transform,1

############
### ENVS ###
############
env=GDK_BACKEND,wayland,x11,*
env=QT_QPA_PLATFORM,wayland;xcb
env=SDL_VIDEODRIVER,wayland
env=CLUTTER_BACKEND,wayland
env=XDG_CURRENT_DESKTOP,Hyprland
env=XDG_SESSION_TYPE,wayland
env=XDG_SESSION_DESKTOP,Hyprland
env=QT_AUTO_SCREEN_SCALE_FACTOR,1
env=QT_QPA_PLATFORM,wayland;xcb
env=QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env=QT_QPA_PLATFORMTHEME,qt5ct
env=GBM_BACKEND,nvidia-drm
env=__GLX_VENDOR_LIBRARY_NAME,nvidia
env=LIBVA_DRIVER_NAME,nvidia
# Steam fix lag after 40 minutes
env=LD_PRELOAD,

#############
### EXECS ###
#############
exec-once=ags run
exec-once=dunst
exec-once=hyprctl setcursor Vimix-Cursors 32
exec-once=hyprpaper

###############
### GENERAL ###
###############
general {
    allow_tearing=true
    border_size=1
    col.active_border=rgb(b8b8b8)
    col.inactive_border=rgb(343434)
    col.nogroup_border=rgb(b8b8b8)
    col.nogroup_border_active=rgb(343434)
    gaps_in=10
    gaps_out=20
    hover_icon_on_border=false
    layout=dwindle
    resize_corner=0
}

######################
### LOOKS AND FEEL ###
######################
animations {
    bezier=main,0,0.55,0.45,1
    animation=windows,1,3,main,slide top
    animation=workspaces,1,3,main,slide
    enabled=true
}

decoration {
    blur {
        enabled=false
    }
#   drop_shadow=false
   rounding=5
    shadow {
        enabled=false
    }
}

#############
### INPUT ###
#############
input {
    accel_profile=flat
    kb_layout=fr
    sensitivity=0.0
    touchdevice {
        enabled=false
    }
}

############
### MISC ###
############
misc {
    disable_hyprland_logo=true
    disable_splash_rendering=true
}

#############
### BINDS ###
#############
binds {
    workspace_back_and_forth=true
}

##############
### CURSOR ###
##############
cursor {
    no_hardware_cursors=1
}

################
### BINDINGS ###
################
#bind=SUPER,code:111,overview,toggle
bind=SUPER,code:114,workspace,+1
bind=SUPER,code:113,workspace,-1
bind=SUPER_ALT,code:114,movetoworkspace,+1
bind=SUPER_ALT,code:113,movetoworkspace,-1
bind=SUPER,code:9,killactive,
bind=,code:95,fullscreen,0
bind=SUPER,code:37,togglefloating,
bind=SUPER,code:55,pseudo,

bind=SUPER_SHIFT,code:39,exec, hyprshot -m region --clipboard-only
bind=SUPER,code:49,exec,wofi --show drun
bind=SUPER,code:24,exec,kitty
bind=SUPER,code:25,exec,zen
bind=SUPER,code:26,exec,zeditor

bind=,code:172,exec,playerctl play-pause
bind=,code:171,exec,playerctl next
bind=,code:173,exec,playerctl previous
bind=,code:121,exec,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

bindm=SUPER,mouse:272,movewindow
bindm=SUPER,mouse:273,resizewindow

####################
### WINDOW RULES ###
####################
windowrulev2=float, class:^(wofi)$
windowrulev2=float, title:^(Picture-in-Picture)$



##################
### WORKSPACES ###
##################
workspace=1,monitor:HDMI-A-1
workspace=2,monitor:HDMI-A-1
workspace=3,monitor:HDMI-A-1
workspace=4,monitor:HDMI-A-1
workspace=5,monitor:HDMI-A-1
workspace=6,monitor:HDMI-A-1
workspace=7,monitor:HDMI-A-1
workspace=8,monitor:HDMI-A-1
workspace=9,monitor:DP-2
